a='welcome to the calculator'
print(a.center(150).upper())
print()
print('Divison')
a=int(input('ENTER THE VALUE of X:'))
b=int(input('ENTER THE VALUE of Y:'))
print(a,'/',b,'=',a/b,)
print()

print('Addtition')
a=int(input('ENTER THE VALUE of X:'))
b=int(input('ENTER THE VALUE of Y:'))
print(a,'+',b,'=',a+b,)
print()
print('Subtraction')
a=int(input('ENTER THE VALUE of X:'))
b=int(input('ENTER THE VALUE of Y:'))
print(a,'-',b,'=',a-b,)
print()
print('Modulus')
a=int(input('ENTER THE VALUE of X:'))
b=int(input('ENTER THE VALUE of Y:'))
print(a,'%',b,'=',a%b,)
print()
print('Multiply')
a=int(input('ENTER THE VALUE of X:'))
b=int(input('ENTER THE VALUE of Y:'))
print(a,'X',b,'=',a*b,)
